version: "3"
services:
  server:
    image: auth_server
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    networks:
      - network
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8
    networks:
      - network
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=authdb
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 30s
      retries: 10

networks:
  network: